import path from "node:path";
import { logger } from "../utils/logger.js";
import { loadLocalConfig } from "../core/config.js";
import {
  loadRepository,
  findSkill
} from "../core/repository.js";
import {
  fetchRepo,
  pullBranch,
  hasLocalChanges,
  checkoutBranch,
  addAndCommit,
  pushBranch
} from "../core/git.js";
import { ghCreatePr, requireGhAuth } from "../core/github.js";
import {
  validateSkill,
  DEFAULT_VALIDATION_OPTIONS
} from "../core/validator.js";
import { getConnectedWorkspace } from "./repo-connect.js";
import { SkillSyncError } from "../utils/errors.js";

export interface ProposeOptions {
  name: string;
  message: string;
  draft?: boolean;
  branch?: string;
  allowSecretRisk?: boolean;
}

export async function runPropose(opts: ProposeOptions): Promise<void> {
  await requireGhAuth();
  const config = await loadLocalConfig();
  const { workspace } = await getConnectedWorkspace();
  const repo = await loadRepository(workspace);
  const skill = await findSkill(repo, opts.name);
  const branch = config.defaultBranch || repo.config.defaultBranch;

  const report = await validateSkill(skill, {
    ...DEFAULT_VALIDATION_OPTIONS,
    scanSecrets:
      repo.config.security.scanForSecrets && !opts.allowSecretRisk
  });
  if (!report.ok) {
    logger.error(`Validation failed for ${skill.metadata.name}:`);
    for (const issue of report.issues) {
      logger.error(`  [${issue.code}] ${issue.message}`);
    }
    throw new SkillSyncError(
      "VALIDATION_FAILED",
      `Skill "${opts.name}" failed validation. Fix the issues or pass --allow-secret-risk for secret findings only.`
    );
  }

  logger.step("Fetching latest from origin");
  await fetchRepo(workspace);
  await checkoutBranch(workspace, branch);
  await pullBranch(workspace, branch);

  if (!(await hasLocalChanges(workspace))) {
    throw new SkillSyncError(
      "GIT_OPERATION_FAILED",
      "No local changes to propose. Edit the skill files first."
    );
  }

  const branchName = opts.branch ?? generateBranchName(opts.name);
  logger.step(`Creating branch ${branchName}`);
  await checkoutBranch(workspace, branchName, true);

  const relSkillPath = path.relative(workspace, skill.folder);
  const commitSha = await addAndCommit(
    workspace,
    [relSkillPath],
    opts.message
  );
  logger.success(`Committed ${commitSha.slice(0, 7)}: ${opts.message}`);

  logger.step("Pushing branch");
  await pushBranch(workspace, branchName);

  const prUrl = await ghCreatePr({
    cwd: workspace,
    title: opts.message,
    body: buildPrBody(opts, skill.metadata.name, commitSha),
    base: branch,
    head: branchName,
    draft: opts.draft
  });
  logger.success(`Pull Request created: ${prUrl}`);
}

function generateBranchName(skillName: string): string {
  const ts = new Date().toISOString().slice(0, 10);
  return `skillsync/${skillName}-${ts}`;
}

function buildPrBody(
  opts: ProposeOptions,
  skillName: string,
  commitSha: string
): string {
  return [
    `Proposed via SkillSync.`,
    ``,
    `**Skill:** \`${skillName}\``,
    `**Commit:** \`${commitSha.slice(0, 7)}\``,
    ``,
    `### Change summary`,
    ``,
    opts.message,
    ``,
    `---`,
    `_Auto-generated by skillsync propose._`
  ].join("\n");
}
